In [1]:
import numpy as np

In [2]:
array = [
        [
            0.5,
            0.0,
            0.0
        ],
        [
            0.0,
            0.5,
            0.0
        ],
        [
            0.0,
            0.0,
            0.5
        ]
    ]
print(a1)

NameError: name 'a1' is not defined

In [3]:
print(array)

[[0.5, 0.0, 0.0], [0.0, 0.5, 0.0], [0.0, 0.0, 0.5]]


In [4]:
a = np.array(array)

In [5]:
print(a)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [6]:
print(array.ndim)

AttributeError: 'list' object has no attribute 'ndim'

In [7]:
print(a.ndim)

2


In [8]:
a1 = np.([0.5 0.  0. ])
print(a1.ndim)

SyntaxError: invalid syntax (<ipython-input-8-33a23af89474>, line 1)

In [9]:
a1 = np.([0.5 0.  0. ])

SyntaxError: invalid syntax (<ipython-input-9-1ad3e75b8783>, line 1)

In [10]:
a1 = np.array([0.5 0.  0. ])

SyntaxError: invalid syntax (<ipython-input-10-664c1447484d>, line 1)

In [11]:
a1 = np.array([0.5, 0. , 0. ])

In [12]:
print(a1.ndim)

1


In [13]:
a2 = np.array(0.5, 0. , 0. )
print(a2.ndim)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
a3 = np.array([6,6,3])
print(np.diag(a3))

[[6 0 0]
 [0 6 0]
 [0 0 3]]


In [15]:
a4 = np.array([1.5, 4, 3])
print(np.diag(a4))

[[1.5 0.  0. ]
 [0.  4.  0. ]
 [0.  0.  3. ]]
